// ts_repo/drt_repos/level_6/drt-template-dapp-nextjs/drt-template-dapp-nextjs-3eff487591b32eafb6656d424dca2f71e5cd15a0/src/components/DrtLink/DrtLink.tsx
import type { PropsWithChildren } from 'react';
import { WithClassnameType } from '@/types';
import Link from 'next/link';

interface DrtLinkPropsType extends PropsWithChildren, WithClassnameType {
  to: string;
}

export const DrtLink = ({
  to,
  children,
  className = 'inline-block rounded-lg px-3 py-2 text-center hover:no-underline my-0 bg-blue-600 text-white hover:bg-blue-700 ml-2 mr-0'
}: DrtLinkPropsType) => {
  return (
    <Link href={to} className={className}>
      {children}
    </Link>
  );
};

// ts_repo/drt_repos/level_6/drt-template-dapp-angular/drt-template-dapp-angular-09f9521c453a2f9b79aa479668ce0d8563c97cce/src/app/components/drt-link/drt-link.component.ts
import { Component, Input } from '@angular/core';
import { RouterModule } from '@angular/router';

@Component({
  selector: 'app-drt-link',
  standalone: true,
  imports: [RouterModule],
  templateUrl: './drt-link.component.html',
  styleUrls: ['./drt-link.component.css']
})
export class DrtLinkComponent {
  @Input() to!: string;
  @Input() className = 'inline-block rounded-lg px-3 py-2 text-center hover:no-underline my-0 bg-blue-600 text-white hover:bg-blue-700 ml-2 mr-0';
}
